language: node_js

node_js:
- 0.11

env:
  global:
  - secure: NN8Ev2bYZzsfhj3OXspWwaM4TP3HEy8SpJwGvYj4oqomrlKGxSNyJSsroB/XuYLWEINnNV4An+7WnweT5ScIVJz0lQxaJOVbfwYwFtPbzD++o29TOFhsj+kAtvYY/ZrukfqYhqI7nDJQ8dlP5EPDikR0itnJ+NK/WUq+3WG6FAQ=
  - secure: gFAeFU1mHbVVJieRlRkL2kSUWiiQkQfviUQFzrnQyxKmUVgDUVbXUFBARi4KqQLSDNeyODXJdbjX4nhEHL2hI/hgsNtvc+4XNzvWE8mZvkBPqbtkbJRnWwqBPUXOLLSgBiiucfK3nLRlZ2GXM/9/x9gM3DsGMN3Ac5xoqK5dq5U=

before_script:
  - npm install grunt-cli -g
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash

script:
  - grunt default:travis